#!/usr/bin/env bash
# Install a git pre-commit hook that keeps listing-review.html in sync whenever
# staged files under the app root's fastlane/ tree change.
#
# Usage: install-review-hook.sh [<app-root>]    (default: current directory)
# Exit:  0 = installed/updated hook, 2 = usage / not a git worktree / can't install.
#
# The refresh logic lives in a generated `listing-kit-review` script next to the
# hook. It rebuilds the page from the STAGED tree (so it matches the commit, not
# unstaged edits), handles every registered app root, and never blocks a commit.
# An existing pre-commit hook is left intact:
#   - shell hook  → one call line is inserted after its shebang; the rest of the
#                   hook runs exactly as before (same exit status)
#   - other hooks → moved to pre-commit.local and exec'd by a small wrapper
# Rerunning adds the app root to the list; hooks from listing-kit ≤0.2 (an inline
# BEGIN/END block) are migrated. Honors linked worktrees and core.hooksPath.
set -euo pipefail

ROOT="${1:-.}"
[ -d "$ROOT" ] || { echo "Not a directory: $ROOT" >&2; exit 2; }

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_REVIEW="$SELF_DIR/build-review.sh"
[ -x "$BUILD_REVIEW" ] || { echo "Missing executable: $BUILD_REVIEW" >&2; exit 2; }

git -C "$ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1 || {
  echo "Not inside a git worktree: $ROOT" >&2
  exit 2
}

# --git-path is relative to $ROOT unless git returns an absolute path.
hook_dir="$(git -C "$ROOT" rev-parse --git-path hooks)"
case "$hook_dir" in
  /*) ;;
  *) hook_dir="$(cd "$ROOT" && pwd)/$hook_dir" ;;
esac
mkdir -p "$hook_dir"
hook="$hook_dir/pre-commit"
runner="$hook_dir/listing-kit-review"
CALL_MARK='# listing-kit review refresh'
call="\"\$(dirname \"\$0\")/listing-kit-review\" || true   $CALL_MARK"

# App root relative to the worktree root ("" at the root), without trailing slash.
app_rel="$(git -C "$ROOT" rev-parse --show-prefix)"
app_rel="${app_rel%/}"

# ---- registered apps: keep existing ones (shell-quoted, as written), add this one ----
apps=()
add_app(){ local a; for a in ${apps[@]+"${apps[@]}"}; do [ "$a" = "$1" ] && return; done; apps+=("$1"); }
if [ -f "$runner" ]; then
  while IFS= read -r a; do add_app "$a"; done < <(sed -n 's/^apps+=(\(.*\))$/\1/p' "$runner")
fi
if [ -f "$hook" ] && grep -q '# BEGIN listing-kit review hook' "$hook"; then
  legacy="$(sed -n 's/^listing_kit_app_rel=//p' "$hook" | head -1)"
  [ -n "$legacy" ] && add_app "$legacy"
fi
printf -v q "%q" "$app_rel"
add_app "$q"

# ---- the runner (fully generated) ----
printf -v build_review_q "%q" "$BUILD_REVIEW"
{
  cat <<EOF
#!/usr/bin/env bash
# Generated by listing-kit install-review-hook.sh; rerun it to update (edits here
# are overwritten). Rebuilds listing-review.html from the STAGED fastlane/ tree of
# each app below and stages it. Never blocks a commit: problems are warnings.
build_review=$build_review_q
apps=()
EOF
  for a in "${apps[@]}"; do echo "apps+=($a)"; done
  cat <<'EOF'

warn(){ echo "listing-kit: $*" >&2; }
if [ ! -x "$build_review" ]; then
  warn "$build_review not found; listing-review.html not refreshed."
  warn "rerun install-review-hook.sh from the current listing-kit install."
  exit 0
fi
cd "$(git rev-parse --show-toplevel)" || exit 0

for app in "${apps[@]}"; do
  p="${app:+$app/}"
  git diff --cached --quiet -- "${p}fastlane/" && continue
  if [ -z "$(git ls-files -- "${p}fastlane/")" ]; then   # listing removed entirely
    git rm -q --cached --ignore-unmatch -- "${p}listing-review.html" && rm -f -- "${p}listing-review.html"
    continue
  fi
  # Snapshot what build-review reads (listing, flows, iPad signals) from the index.
  snap="$(mktemp -d)"
  git ls-files -z -- "${p}fastlane/" "${p}.listing-kit/flows/" "${p}app.json" "${p}app.config.*" \
      ":(glob)${p}**/*.pbxproj" ":(glob)${p}**/Info.plist" \
    | git checkout-index -z --stdin --prefix="$snap/"
  if "$build_review" "$snap/${app:-.}" >/dev/null 2>&1; then
    cp "$snap/${p}listing-review.html" "${p}listing-review.html" && git add -- "${p}listing-review.html"
  else
    warn "build-review.sh failed for ${app:-the repo root}; listing-review.html not refreshed."
  fi
  rm -rf "$snap"
done
exit 0
EOF
} > "$runner"
chmod +x "$runner"

# ---- wire the runner into pre-commit without changing the existing hook's behavior ----
if [ -f "$hook" ] && grep -q '# BEGIN listing-kit review hook' "$hook"; then
  tmp="$(mktemp)"
  awk '/# BEGIN listing-kit review hook/{skip=1;next} /# END listing-kit review hook/{skip=0;next} !skip' "$hook" > "$tmp"
  # Only our own old header left (shebang + set line)? Then start fresh.
  if [ -z "$(grep -vE '^(#!.*|set -euo pipefail|[[:space:]]*)$' "$tmp")" ]; then rm -f "$hook" "$tmp"
  else cat "$tmp" > "$hook"; rm -f "$tmp"; fi
fi

if [ ! -f "$hook" ]; then
  printf '#!/bin/sh\n%s\n' "$call" > "$hook"
elif grep -qF "$CALL_MARK" "$hook"; then
  :   # already wired
elif head -1 "$hook" | grep -qE '^#!.*[/ ](ba|da|k|z)?sh([[:space:]].*)?$' || ! head -1 "$hook" | grep -q '^#!'; then
  tmp="$(mktemp)"
  if head -1 "$hook" | grep -q '^#!'; then
    { head -1 "$hook"; echo "$call"; tail -n +2 "$hook"; } > "$tmp"
  else
    { echo "$call"; cat "$hook"; } > "$tmp"
  fi
  cat "$tmp" > "$hook"; rm -f "$tmp"
else
  local_hook="$hook_dir/pre-commit.local"
  [ -e "$local_hook" ] && {
    echo "Can't install: $hook is not a shell script and $local_hook already exists." >&2
    exit 2
  }
  mv "$hook" "$local_hook"
  printf '#!/bin/sh\n%s\nexec "$(dirname "$0")/pre-commit.local" "$@"\n' "$call" > "$hook"
  echo "Moved your existing pre-commit hook to $local_hook (it still runs, and its exit status decides the commit)."
fi
chmod +x "$hook"

echo "Installed listing-kit review hook: $hook (apps: ${apps[*]})"
